SUPABASE_URL= "https://hpsexkbugkkuglmojstd.supabase.co"
SUPABASE_KEY= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhwc2V4a2J1Z2trdWdsbW9qc3RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MzUzNDksImV4cCI6MjA2MzMxMTM0OX0.umubCnMZp4GJ2uglEygWSbprfmWZtUP4YTV-FXm7fYI"
            